services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=simple-cms
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  mongodb_data: